// Embedded markdown content used by materialization.

export const MISSION_SKILL_CONTENT = `---
name: mission
description: Perform a coding task — plan, implement, validate, and deliver via pull request
---

# Mission Skill

## Critical Rules
1. **Stay in your work tree** — your \`cwd\` is your root; do not read or modify files outside it
2. **Work in a branch** — naming convention: \`<agent-name>/<mission-name>\` (keep names short)
3. **Write new tests** — new functionality must include tests to prevent regressions

## Workflow

1. Create your working branch, based off origin/main
2. Ask clarifying questions of the user to ensure the outcome is fully captured
3. Create a test plan with test cases and acceptance criteria
4. Proceed to implement the work, committing regularly with descriptive messages
5. Validate your changes by invoking the \`/validate-changes\` skill
6. Fix any failures and re-validate; repeat until all checks pass
7. Commit any remaining work and push your branch to remote
8. Create a PR by invoking the \`/create-pr\` skill
9. Return to standby by invoking the \`/go-standby\` skill

**Clean State** — your standby state should be clean from untracked or uncommitted changes; if this is not the case let the user know before starting next work
`;

export const CREATE_PR_SKILL_CONTENT = `---
name: create-pr
description: Create a pull request for the current branch using the project's configured source control provider
---

# Create Pull Request

Create a pull request for the current branch targeting main. Include a rich description covering the changes, test cases, and any manual validation needed.

@@If(github)
## Creating a Pull Request (GitHub)

Use the GitHub CLI to create a PR:

\`\`\`bash
gh pr create --title "<title>" --body "$(cat <<'EOF'
## Summary
<1-3 bullet points summarizing the change>

## Changes
<detailed list of changes>

## Test Plan
- [ ] <test cases and acceptance criteria>

## Manual Validation
<any manual steps needed to verify>
EOF
)"
\`\`\`
@@EndIf
@@If(azure-devops)
## Creating a Pull Request (Azure DevOps)

Use the Azure CLI to create a PR:

\`\`\`bash
az repos pr create \\
  --title "<title>" \\
  --description "## Summary
<1-3 bullet points summarizing the change>

## Changes
<detailed list of changes>

## Test Plan
- [ ] <test cases and acceptance criteria>

## Manual Validation
<any manual steps needed to verify>" \\
  --source-branch <current-branch> \\
  --target-branch main
\`\`\`
@@EndIf
`;

export const GO_STANDBY_SKILL_CONTENT = `---
name: go-standby
description: Return to the standby branch and prepare for the next task
---

# Go Standby

Return to your standby branch and prepare for the next task.

## Steps

1. Check for uncommitted changes — if any exist, warn the user before proceeding
2. Switch to your standby branch:
   \`\`\`bash
   git checkout @@StandbyBranch
   \`\`\`
3. Pull latest from main:
   \`\`\`bash
   git pull origin main
   \`\`\`
4. Verify your working tree is clean
5. Await further instructions
`;

export const BUILD_SKILL_CONTENT = `---
name: build
description: Build the project using the configured build command
---

# Build

Run the project build:

\`\`\`bash
@@BuildCommand
\`\`\`

If the build fails, analyze the error output and attempt to fix the issue. Re-run until the build succeeds.
`;

export const TEST_SKILL_CONTENT = `---
name: test
description: Run the project test suite using the configured test command
---

# Test

Run the project tests:

\`\`\`bash
@@TestCommand
\`\`\`

If tests fail, analyze the failures and fix the underlying issues. Re-run until all tests pass.
`;

export const LINT_SKILL_CONTENT = `---
name: lint
description: Run the project linter using the configured lint command
---

# Lint

Run the project linter:

\`\`\`bash
@@LintCommand
\`\`\`

If there are lint errors, fix them. Re-run until the linter passes cleanly.
`;

export const VALIDATE_CHANGES_SKILL_CONTENT = `---
name: validate-changes
description: Run full validation — build, test, and lint — to verify changes before pushing
---

# Validate Changes

Run the full validation pipeline to ensure your changes are ready to push.

## Steps

1. **Build** the project:
   \`\`\`bash
   @@BuildCommand
   \`\`\`
2. **Run tests**:
   \`\`\`bash
   @@TestCommand
   \`\`\`
3. **Run linter**:
   \`\`\`bash
   @@LintCommand
   \`\`\`

If any step fails, fix the issues and re-run the full pipeline. Do not proceed until all steps pass.
`;
export const CLUBHOUSE_MODE_README_CONTENT = `# Clubhouse Mode — Self-Edit Guide

This file is generated by Clubhouse. It documents where settings live on
disk and how to change them without using the UI.

> **Note:** This file is regenerated whenever Clubhouse refreshes it (on
> agent wake and on project open during a session). Local edits will be
> overwritten — treat \`.clubhouse/settings.json\`, \`.clubhouse/agents.json\`,
> \`.clubhouse/skills/\`, \`.clubhouse/missions/\`, and \`.clubhouse/personas/\` as
> the editable surfaces.

---

## Settings layers

Three layers, all editable from disk:

| Layer            | File                                                  | Scope                          |
|------------------|-------------------------------------------------------|--------------------------------|
| App-wide         | \`<userData>/clubhouse-mode-settings.json\`             | enabled flag, project overrides|
| Project          | \`.clubhouse/settings.json\`                            | defaults applied to all agents |
| Per-agent        | \`.clubhouse/agents.json\`                              | overrides for a single agent   |

\`<userData>\` is Electron's per-user app data dir:
- macOS: \`~/Library/Application Support/Clubhouse/\`
- Linux: \`~/.config/Clubhouse/\`
- Windows: \`%APPDATA%\\Clubhouse\\\`

**Precedence** (highest first): per-agent → project override → app-wide.

### Toggle Clubhouse Mode for this project (override)

Edit \`<userData>/clubhouse-mode-settings.json\`:

\`\`\`json
{
  "enabled": true,
  "projectOverrides": {
    "/absolute/path/to/this/project": true
  }
}
\`\`\`

Set the override to \`false\` to disable just this project while keeping the
app-wide setting unchanged. Delete the key to clear the override.

### Toggle per-agent override

Find the agent in \`.clubhouse/agents.json\` and add:

\`\`\`json
{ "clubhouseModeOverride": true }
\`\`\`

Setting it to \`false\` opts that agent out of materialization on wake.

---

## Project defaults (\`.clubhouse/settings.json\`)

The \`agentDefaults\` object is what gets materialized into each agent worktree
when Clubhouse Mode runs:

\`\`\`json
{
  "agentDefaults": {
    "instructions": "...CLAUDE.md template with @@wildcards...",
    "permissions": { "allow": ["Read(@@Path**)"], "deny": ["Read(../**)"] },
    "mcpJson": "{ \\"mcpServers\\": { ... } }",
    "freeAgentMode": false,
    "sourceControlProvider": "github",
    "buildCommand": "npm run build",
    "testCommand": "npm test",
    "lintCommand": "npm run lint",
    "mission": "implement-and-ship"
  }
}
\`\`\`

Any agent without an explicit override inherits these.

---

## Per-agent overrides (\`.clubhouse/agents.json\`)

Each entry in the \`agents\` array supports per-agent overrides:

\`\`\`json
{
  "id": "durable_...",
  "name": "bold-falcon",
  "branch": "bold-falcon/standby",
  "persona": "qa",
  "mission": "investigate-and-report",
  "buildCommand": "npm run build",
  "testCommand": "npm test",
  "lintCommand": "npm run lint",
  "sourceControlProvider": "github",
  "clubhouseModeOverride": true,
  "mcpIds": ["github"],
  "model": "claude-opus-4-7"
}
\`\`\`

Editable fields: \`persona\`, \`mission\`, \`buildCommand\`, \`testCommand\`,
\`lintCommand\`, \`sourceControlProvider\`, \`clubhouseModeOverride\`,
\`freeAgentMode\`, \`model\`, \`orchestrator\`, \`structuredMode\`, \`mcpIds\`,
\`mcpConfigs\`, \`mcpOverride\`.

Each of \`buildCommand\`, \`testCommand\`, \`lintCommand\`, and
\`sourceControlProvider\` is a per-agent override of the matching wildcard; when
unset the agent inherits the project default from \`agentDefaults\`. These same
overrides are what the per-agent **Wildcards** settings form writes when an
agent is managed by Clubhouse Mode (override disabled).

Edits take effect on the next agent wake (which re-materializes the worktree).

---

## Preserved skills (\`.clubhouse/skills/\`)

Skills live in \`.clubhouse/skills/<skill-name>/SKILL.md\`. On materialization
they are copied to each agent worktree at \`.claude/skills/<skill-name>/\`
with \`@@\` wildcards substituted.

- **Edit** an existing skill: change \`.clubhouse/skills/<name>/SKILL.md\`.
- **Add** a new skill: create \`.clubhouse/skills/<new-name>/SKILL.md\` with a
  YAML frontmatter \`name:\` and \`description:\`, then a markdown body.
- **Delete**: remove the directory. On next wake, the skill is pruned from
  every agent worktree automatically.

Default skills (\`mission\`, \`test\`, \`build\`, \`lint\`, \`validate-changes\`,
\`create-pr\`, \`go-standby\`) are written on enable but never overwritten —
edit them freely.

---

## Missions (\`.clubhouse/missions/\`)

A **mission** is a reusable end-to-end task flow (e.g. \`look at spec → fix →
add tests → run until green → open PR → return to standby\`). Missions are
flat markdown files under \`.clubhouse/missions/\`; the filename (minus
\`.md\`) is the mission ID.

\`\`\`
.clubhouse/missions/
  implement-and-ship.md
  investigate-and-report.md
  quick-bugfix.md
\`\`\`

At materialization, the content of the active mission file is substituted
for the \`@@Mission\` wildcard everywhere it appears (default CLAUDE.md
template, skills, permissions, etc.).

**Selecting a mission**:
- Set \`agentDefaults.mission\` in \`.clubhouse/settings.json\` for the
  project-wide default.
- Set \`mission\` on an agent in \`.clubhouse/agents.json\` to override per-agent.
- Per-agent wins. Either value is the mission ID (filename without \`.md\`).

If the mission file does not exist, \`@@Mission\` resolves to an empty string —
the rest of materialization still succeeds.

---

## Personas (\`.clubhouse/personas/\`)

A **persona** layers a role (e.g. \`qa\`, \`researcher\`, \`judge\`) onto an
agent. The content is substituted for the \`@@Persona\` wildcard, or appended to
the instructions when the template doesn't reference the token.

Clubhouse ships a built-in persona library. To customize, author an on-disk
persona file — a flat markdown file where the filename (minus \`.md\`) is the
persona ID. There are two on-disk scopes:

\`\`\`
.clubhouse/personas/        # project-scoped — this project only
  qa.md                     # overrides the built-in "qa" persona here
  my-reviewer.md            # a project-specific persona

~/.clubhouse/personas/      # user-global — reusable across ALL your projects
  my-reviewer.md            # author once, use in any project
\`\`\`

At materialization, persona content resolves by precedence: **project →
user-global → built-in**. A \`.clubhouse/personas/<id>.md\` wins; otherwise a
\`~/.clubhouse/personas/<id>.md\` is used; otherwise the built-in template of the
same ID. Built-ins are never written to disk automatically — they remain
available until you shadow one with a file of the same name. Put personas you
want everywhere in \`~/.clubhouse/personas/\`; use \`.clubhouse/personas/\` to
tweak one only for this project.

**Selecting a persona** works exactly like missions:
- Set \`agentDefaults.persona\` in \`.clubhouse/settings.json\` for the
  project-wide default.
- Set \`persona\` on an agent in \`.clubhouse/agents.json\` to override per-agent.
- Per-agent wins. Either value is the persona ID.

---

## Wildcards available to all templates

| Token                       | Resolves to                                          |
|-----------------------------|------------------------------------------------------|
| \`@@AgentName\`               | e.g. \`bold-falcon\`                                   |
| \`@@StandbyBranch\`           | e.g. \`bold-falcon/standby\`                           |
| \`@@Path\`                    | e.g. \`.clubhouse/agents/bold-falcon/\`                |
| \`@@SourceControlProvider\`   | \`github\` or \`azure-devops\`                           |
| \`@@BuildCommand\`            | from project defaults                                |
| \`@@TestCommand\`             | from project defaults                                |
| \`@@LintCommand\`             | from project defaults                                |
| \`@@Mission\`                 | full markdown content of the active mission file     |
| \`@@Persona\`                 | full markdown content of the active persona template |
| \`@@If(github)…@@EndIf\`      | conditional block, kept only when provider matches   |

Neither \`@@Mission\` nor \`@@Persona\` appear in the built-in default template — add them to your customized \`agentDefaults.instructions\` if you want the content inlined at a specific position. \`@@Persona\` also acts as an "opt out" of the default auto-append behavior: when your template contains the token, the persona content is substituted in place and not appended again at the bottom.

---

## Common edits

| Goal                                       | Edit                                                       |
|--------------------------------------------|------------------------------------------------------------|
| Change project default mission             | \`agentDefaults.mission\` in \`.clubhouse/settings.json\`     |
| Give one agent a different mission         | \`mission\` in that agent's entry in \`.clubhouse/agents.json\`|
| Change project default persona             | \`agentDefaults.persona\` in \`.clubhouse/settings.json\`     |
| Give one agent a different persona         | \`persona\` in that agent's entry in \`.clubhouse/agents.json\`|
| Customize a persona's content              | Author \`.clubhouse/personas/<id>.md\` (overrides built-in)  |
| Override a command for one agent           | \`buildCommand\`/\`testCommand\`/\`lintCommand\` in \`.clubhouse/agents.json\` |
| Tweak a skill body                         | Edit the file under \`.clubhouse/skills/<name>/SKILL.md\`    |
| Add a new wildcard target                  | (Code change — see \`src/shared/wildcard-replacer.ts\`)      |
| Disable Clubhouse Mode for this project    | \`projectOverrides[<path>] = false\` in user settings        |
| Opt one agent out of materialization       | \`clubhouseModeOverride: false\` in that agent's entry       |

---

## What gets pruned vs preserved

On every wake, materialization:

- **Overwrites** the agent's \`CLAUDE.md\`, \`.claude/settings.local.json\` permissions block, and \`.mcp.json\` from the project defaults.
- **Copies** every \`.clubhouse/skills/*\` and \`.clubhouse/agent-templates/*\` into the worktree with wildcards resolved.
- **Prunes** worktree skills/templates that no longer exist in source.
- **Never touches** any other file in the worktree, including agent-local edits to skills that don't exist in source.
`;
