/**
 * v0.9 SDK Surface Contract
 *
 * This file declares the exact API surface added in v0.9. It imports the real
 * types from plugin-types.ts and uses compile-time assertions to prove that
 * the surface declared here matches the actual implementation.
 *
 * When this version is stable, the file is hash-locked. Any change to this
 * file will fail CI unless the hash is explicitly updated via:
 *   node scripts/compute-sdk-hash.mjs update v0.9
 *
 * DO NOT EDIT this file for a stable version without following the patch
 * process documented in docs/sdk-versioning.md.
 */
import type {
  PluginKind,
  PluginCompanionConfig,
  PluginMcpToolDefinition,
  PluginMcpToolResult,
  McpAPI,
  AgentsAPI,
  PluginPermission,
  PluginManifest,
  Disposable,
} from '../plugin-types';

// ── v0.9 type surface ──────────────────────────────────────────────────

/**
 * PluginKind must include 'workspace' (added in v0.9).
 */
type AssertWorkspaceKind = Extract<PluginKind, 'workspace'>;
const _kindCheck: AssertWorkspaceKind = 'workspace' as AssertWorkspaceKind;
void _kindCheck;

/**
 * PluginCompanionConfig — workspace plugin companion agent configuration.
 */
type AssertCompanionConfig = {
  enabled: PluginCompanionConfig['enabled'];        // boolean
  defaultModel: PluginCompanionConfig['defaultModel']; // string | undefined
  systemPrompt: PluginCompanionConfig['systemPrompt']; // string | undefined
};
const _companionCheck: AssertCompanionConfig = null! as AssertCompanionConfig;
void _companionCheck;

/**
 * PluginMcpToolDefinition — tool definitions contributed by plugins.
 */
type AssertMcpToolDef = {
  name: PluginMcpToolDefinition['name'];               // string
  description: PluginMcpToolDefinition['description'];  // string
  inputSchema: PluginMcpToolDefinition['inputSchema'];  // Record<string, unknown>
};
const _mcpToolDefCheck: AssertMcpToolDef = null! as AssertMcpToolDef;
void _mcpToolDefCheck;

/**
 * PluginMcpToolResult — result returned by a plugin MCP tool handler.
 */
type AssertMcpToolResult = {
  content: PluginMcpToolResult['content'];   // Array<{ type: 'text'; text: string }>
  isError: PluginMcpToolResult['isError'];   // boolean | undefined
};
const _mcpToolResultCheck: AssertMcpToolResult = null! as AssertMcpToolResult;
void _mcpToolResultCheck;

/**
 * McpAPI — MCP tool contribution methods (v0.9+).
 */
type AssertMcpAPI = {
  contributeTools: McpAPI['contributeTools'];       // (tools: PluginMcpToolDefinition[]) => Promise<void>
  removeTools: McpAPI['removeTools'];               // () => Promise<void>
  listContributedTools: McpAPI['listContributedTools']; // () => Promise<string[]>
  onToolCall: McpAPI['onToolCall'];                 // (handler) => Disposable
};
const _mcpApiCheck: AssertMcpAPI = null! as AssertMcpAPI;
void _mcpApiCheck;

/**
 * AgentsAPI companion methods — added in v0.9.
 */
type AssertCompanionMethods = {
  spawnCompanion: AgentsAPI['spawnCompanion'];
  getCompanionStatus: AgentsAPI['getCompanionStatus'];
  getCompanionWorkspace: AgentsAPI['getCompanionWorkspace'];
};
const _companionMethodsCheck: AssertCompanionMethods = null! as AssertCompanionMethods;
void _companionMethodsCheck;

/**
 * v0.9 permissions: 'companion' and 'mcp.tools'.
 */
type AssertCompanionPermission = Extract<PluginPermission, 'companion'>;
type AssertMcpToolsPermission = Extract<PluginPermission, 'mcp.tools'>;
const _permCompanion: AssertCompanionPermission = 'companion' as AssertCompanionPermission;
const _permMcpTools: AssertMcpToolsPermission = 'mcp.tools' as AssertMcpToolsPermission;
void _permCompanion;
void _permMcpTools;

/**
 * PluginManifest.companion field (v0.9+).
 */
type AssertManifestCompanion = PluginManifest['companion'];
const _manifestCompanionCheck: AssertManifestCompanion = null! as AssertManifestCompanion;
void _manifestCompanionCheck;

/**
 * PluginManifest.kind must accept 'workspace' (v0.9+).
 */
type AssertManifestKind = Extract<NonNullable<PluginManifest['kind']>, 'workspace'>;
const _manifestKindCheck: AssertManifestKind = 'workspace' as AssertManifestKind;
void _manifestKindCheck;

// ── Signature freeze ───────────────────────────────────────────────────
// The following type aliases freeze the exact function signatures so that
// any change to parameter types or return types breaks compilation.

type FreezeContributeTools = (tools: PluginMcpToolDefinition[]) => Promise<void>;
type FreezeRemoveTools = () => Promise<void>;
type FreezeListContributedTools = () => Promise<string[]>;
type FreezeOnToolCall = (handler: (toolName: string, args: Record<string, unknown>) => Promise<PluginMcpToolResult>) => Disposable;

type FreezeSpawnCompanion = (options?: { model?: string; systemPrompt?: string }) => Promise<string>;
type FreezeGetCompanionStatus = () => Promise<'sleeping' | 'waking' | 'active' | 'none'>;
type FreezeGetCompanionWorkspace = () => Promise<string>;

// Compile-time assertion: real signatures must be assignable to frozen signatures
const _freezeContribute: FreezeContributeTools = null! as McpAPI['contributeTools'];
const _freezeRemove: FreezeRemoveTools = null! as McpAPI['removeTools'];
const _freezeList: FreezeListContributedTools = null! as McpAPI['listContributedTools'];
const _freezeOnToolCall: FreezeOnToolCall = null! as McpAPI['onToolCall'];
const _freezeSpawn: FreezeSpawnCompanion = null! as AgentsAPI['spawnCompanion'];
const _freezeStatus: FreezeGetCompanionStatus = null! as AgentsAPI['getCompanionStatus'];
const _freezeWorkspace: FreezeGetCompanionWorkspace = null! as AgentsAPI['getCompanionWorkspace'];
void _freezeContribute; void _freezeRemove; void _freezeList; void _freezeOnToolCall;
void _freezeSpawn; void _freezeStatus; void _freezeWorkspace;
